name: flutter_fish
description: "a fish app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_switch: ^0.3.2
  skeletonizer: ^1.4.3 # 骨架屏
  flutter_screenutil: ^5.9.3 # 屏幕适配
  modal_bottom_sheet: ^3.0.0 #弹出层
  hexcolor: ^3.0.1 # 颜色
  easy_refresh: ^3.4.0 # 列表下拉刷新
#  connectivity_plus: ^6.1.3 # 网络状态监听
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.2.3
flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: Circular Std
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf
        - asset: assets/fonts/CircularStd-Medium.otf
          weight: 600
        - asset: assets/fonts/CircularStd-Bold.otf
          weight: 700
        - asset: assets/fonts/CircularStd-Black.otf
          weight: 800